- README.md
- pom.xml
- src/main/java/io/zeebe/containers/ZeebeContainer.java
- src/main/java/io/zeebe/containers/ZeebeEnvironment.java
- src/test/java/io/zeebe/containers/SupportedVersion.java
- upgrades Zeebe version to 0.22.0-alpha2
- adds `ZeebeContainer#withAdvertisedHost`
> feat(containers): add support for 0.22.0-alpha2

- README.md
- pom.xml
- src/main/java/io/zeebe/containers/SupportedVersion.java
- src/main/java/io/zeebe/containers/ZeebeBrokerContainer.java
- removed alpha versions, all supported versions are final now
- WIP: tests run through in IDE, but not on command line -> container timeouts for cluster tests
- storing version in ZeebeBrokerContainer so we can retrieve the correct log output (stored in Enum now)
- moved SupportedVersion to make it accessible from both test and implementation
> #21 update for Zeebe 0.22.1 final

- src/main/java/io/zeebe/containers/BrokerWaitStrategy.java
- src/main/java/io/zeebe/containers/SupportedVersion.java
- src/main/java/io/zeebe/containers/ZeebeBrokerContainer.java
- src/test/java/io/zeebe/containers/ZeebeBrokerContainerTest.java
Changes the wait strategy to wait for a 204 response from the `/ready` endpoint and for the command API to be ready to accept commands. This has the advantage of not being dependent on broker logs and expanding the supported zeebe versions from 0.20.1, 0.21.1 and 0.22.1 to all versions that support the `/ready` endpoint on the 9600 port. It's also possible to use zeebe-test-container with non semver version like SNAPSHOT.
closes #37
> chore(containers): improve wait strategy

- src/main/java/io/zeebe/containers/ZeebeContainer.java
Support shutting down the broker gracefully without killing the container (unless a timeout occurs).
closes #42
> feat(containers): support graceful shutdown

- src/main/java/io/zeebe/containers/ZeebeContainer.java
- src/test/java/io/zeebe/containers/ZeebeBrokerContainerTest.java
- src/test/resources/zeebe.cfg.toml
Fixed the way, temporary file is being opened to store configuration in it. Before is was opened in read-only mode and the exception was thrown.
closes #44
> fix(containers): Zeebe config can be passed through InputStream

- src/main/java/io/zeebe/containers/ZeebeBrokerContainer.java
- src/main/java/io/zeebe/containers/ZeebeStandaloneGatewayContainer.java
- src/test/java/io/zeebe/containers/ZeebeBrokerContainerTest.java
If a user exposed ports while building his/her container, it was previously overwritten on start by us calling `withExposedPorts` instead of `addExposedPort`.
> fix: fixes issue where user exposed ports are overwritten

- src/main/java/io/zeebe/containers/ZeebeBrokerContainer.java
* Default configuration enables debug exporter. There is no way to disable it. So this PR removes it from the default configuration.
> chore(containers): remove debug exporter from default configuration

- pom.xml
The library uses the slf4j-simple implementation, but it's currently a dependency instead of a test dependency, which can result in projects having multiple bindings.
> Ensure SLF4J logging implementation binding is a test dependency

- src/main/java/io/zeebe/containers/cluster/ZeebeClusterBuilder.java
- src/test/java/io/zeebe/containers/cluster/ZeebeClusterBuilderTest.java
I've added the convenience methods to set a docker image for the Zeebe container in the cluster.
closes #139
> feat: add the ability to set specific images via ZeebeClusterBuilder

- pom.xml
- revapi.json
Since we have an issue with vulnerabilities: https://github.com/testcontainers/testcontainers-java/issues/4384 I decided that we should update this dependency by ourselves.
closes #187
> deps: update commons-compress to 1.21

- pom.xml
- src/main/java/io/zeebe/containers/cluster/ZeebeClusterBuilder.java
- src/test/java/io/zeebe/containers/cluster/ZeebeClusterBuilderTest.java
I created three methods to configure parts of the cluster: gateways, brokers, or both. I decided to use the `Consumer` interface instead of `UnaryOperator` because it is much more convenient to implement with `Consumer`.
closes #150
> feat: add methods to configure gateways, brokers or both in the cluster

- README.md
- pom.xml
- src/main/java/io/zeebe/containers/clock/ZeebeClock.java
- src/main/java/io/zeebe/containers/clock/ZeebeClockClient.java
- src/main/java/io/zeebe/containers/clock/ZeebeClockImpl.java
- src/main/java/io/zeebe/containers/clock/ZeebeClockTarget.java
- src/test/java/io/zeebe/containers/clock/ZeebeClockTest.java
- src/test/java/io/zeebe/containers/examples/clock/TriggerTimerCatchEventTest.java
- src/test/java/io/zeebe/containers/examples/clock/TriggerTimerStartEventTest.java
- src/test/resources/simplelogger.properties
This PR adds a high level time traveling API, allowing users to easily read and optionally modify a node's actor clock. The default implementation is an `OpenFeign` based client with minimal dependencies which targets the node's actuator clock endpoint. Note that this only works with Zeebe versions 1.3 and above.
closes #223
> Add a high level time travel API

- .github/workflows/ci.yml
- .mvn/jvm.config
- README.md
- pom.xml
- src/test/java/io/zeebe/containers/ZeebeBrokerNodeTest.java
- src/test/java/io/zeebe/containers/cluster/ZeebeClusterTest.java
- src/test/java/io/zeebe/containers/util/TopologyAssert.java
This PR downgrades the project's build pipeline to Java 8. Since we target Java 8, to ensure that users on Java 8 can use this library, we need to also run our complete pipeline over Java 8. Unfortunately targeting the language level is not enough as that only guarantees newer language features are not used, but does not guarantee things such as using new standard library functions which are not available in Java 8.
> Downgrade project to use Java 8 for the build pipeline

- README.md
- src/test/java/io/zeebe/containers/examples/cluster/ZeebeClusterSingleNodeExampleTest.java
- src/test/java/io/zeebe/containers/examples/cluster/ZeebeClusterWithEmbeddedGatewaysExampleTest.java
- src/test/java/io/zeebe/containers/examples/cluster/ZeebeClusterWithGatewayExampleTest.java
This PR updates the README and the examples to showcase that a `ZeebeCluster`, which implements `Startable`, can be managed by the `Testcontainers` Junit 5 extension. Simply annotate your test with `@Testcontainers`, your cluster with `@Container`, and you're good to go.
> Showcase startable cluster via docs and examples

- pom.xml
Adds flatten-maven-plugin to the build pipeline. This will generate a flattened POM, which removes any POM hierarchy, substitutes all properties, removes non compile dependencies, and more. This solves issues when it comes to dependency management for consumers of this project by greatly reducing how much they have to care when it comes to dependency convergence.
> Flatten deployed POM

- .github/ISSUE_TEMPLATE/type_bug.md
- .github/ISSUE_TEMPLATE/type_docs.md
- .github/ISSUE_TEMPLATE/type_feature.md
- .github/ISSUE_TEMPLATE/type_maintenance.md
- .github/ISSUE_TEMPLATE/type_project.md
- .github/ISSUE_TEMPLATE/type_test.md
- .github/pull_request_template.md
- README.md
- SECURITY.md
- pom.xml
Use spotless to also format documentation, i.e. markdown files.
> Format markdown with spotless

- pom.xml
This PR updates the base Zeebe dependency to 8.0.0. It will require a new release, but if everything works, then just a minor release should be fine.
> Bump Zeebe dependency to 8.0.0

- engine/src/main/java/io/zeebe/containers/engine/ContainerEngine.java
- engine/src/main/java/io/zeebe/containers/engine/ContainerEngineBuilder.java
This PR allows setting an explicit debug receiver port when building your container engine.
> feat(engine): allow setting the exporter receiver port

- .github/workflows/ci.yml
- engine/src/main/java/io/zeebe/containers/engine/ContainerEngine.java
- engine/src/main/java/io/zeebe/containers/engine/ContainerEngineBuilder.java
Deprecates setting only the receiver port and allows passing a pre-configured `DebugReceiver`.
> Allow configuring the debug receiver in general

- core/src/main/java/io/zeebe/containers/ZeebeBrokerNode.java
- core/src/main/java/io/zeebe/containers/util/HostPortForwarder.java
- core/src/test/java/io/zeebe/containers/util/HostPortForwarderTest.java
This PR adds a QoL when using the debug exporter by retrying issues when trying to expose the host port. This is to handle issues when dealing with remote containers, where network issues may introduce temporary connection problems.
related to camunda/zeebe#10287
> fix(core): retry exposing host port up to 5 times

- core/src/main/java/io/zeebe/containers/ZeebeGatewayContainer.java
This PR exposes the gateway's monitoring port by default, since it's quite useful to access actuators for testing.
closes #332
> refactor(core): expose gateway monitoring port by default

- .github/workflows/test.yml
- core/pom.xml
- engine/pom.xml
- pom.xml
> build: remove jdk8 from ci

- core/src/main/java/io/zeebe/containers/ZeebeBrokerContainer.java
- core/src/main/java/io/zeebe/containers/ZeebeContainer.java
- core/src/main/java/io/zeebe/containers/ZeebeGatewayContainer.java
Applies the default start time out to all strategies.
> fix: apply default start timeout every time

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- README.md
- core/pom.xml
- core/src/test/java/io/zeebe/containers/examples/exporter/BrokerWithDebugExporterIT.java
- engine/pom.xml
- engine/src/test/java/io/zeebe/containers/engine/DebugReceiverStreamIT.java
- engine/src/test/java/io/zeebe/containers/engine/ZeebeClusterEngineIT.java
- engine/src/test/java/io/zeebe/containers/engine/ZeebeContainerEngineIT.java
- engine/src/test/java/io/zeebe/containers/engine/examples/ClusterEngineExampleIT.java
- engine/src/test/java/io/zeebe/containers/engine/examples/ContainerEngineExampleIT.java
- engine/src/test/java/io/zeebe/containers/engine/examples/GracePeriodExampleIT.java
- exporter-test/pom.xml
- exporter/pom.xml
- pom.xml
Bump zeebe-test-container to use Java 21 since it relies on some Zeebe internals which are also on 21 at this point.
> refactor: bump to Java 21

- exporter/pom.xml
- pom.xml
This PR downgrades the exporter from Java 21 to Java 17 to keep compatibility with versions < 8.4.
> refactor: downgrade exporter to 17 for < 8.4 compat

- README.md
This PR adds documentation on how to test a custom exporter using this project.
closes #620
> docs: document how to test a custom exporter

- core/src/main/java/io/zeebe/containers/ZeebeVolume.java
- core/src/test/java/io/zeebe/containers/ZeebeVolumeTest.java
- pom.xml
Accesses the internal of testcontainers-java to apply the correct label to `ZeebeVolume`s such that Ryuk (or an alternative `ResourceReaper`) can find the volume and automatically remove it after tests are done.
The tests are a bit hacky because we use reflection to get to the private implementations of `ResourceReaper`.
Closes #656
> fix: automatically cleanup `ZeebeVolume`s

- core/src/test/java/io/zeebe/containers/ZeebeBrokerNodeTest.java
> test: fix flakiness around shared network

- core/src/main/java/io/zeebe/containers/ZeebeBrokerNode.java
- core/src/main/java/io/zeebe/containers/exporter/DebugReceiver.java
- core/src/main/java/io/zeebe/containers/exporter/RecordHandler.java
- exporter/src/main/java/io/zeebe/containers/exporter/DebugExporter.java
- pom.xml
With Apach HTTPComponents httpcore5 5.2.5, the server now matches the request authority, which causes it to drop when the host name is not recognized. This breaks the DebugExporter which uses the internal Testcontainers proxy (`host.testcontainers.org`), whereas the server is expecting `localhost`. The simple fix is to support both access patterns by adding a virtual host, and having both use the same handler (which is already thread-safe, assuming the given consumer is also thread-safe).
> Fix compatibility with Apache httpcore5 5.2.5 by adding a virtual host for Testcontainers' proxy

- README.md
- core/src/main/java/io/zeebe/containers/ZeebeContainer.java
- core/src/main/java/io/zeebe/containers/ZeebeGatewayContainer.java
- core/src/main/java/io/zeebe/containers/ZeebeGatewayNode.java
- core/src/main/java/io/zeebe/containers/ZeebeNode.java
- core/src/main/java/io/zeebe/containers/ZeebePort.java
- core/src/main/java/io/zeebe/containers/ZeebeTopologyWaitStrategy.java
- core/src/main/java/io/zeebe/containers/cluster/ZeebeCluster.java
- core/src/test/java/io/zeebe/containers/ZeebeBrokerNodeTest.java
- core/src/test/java/io/zeebe/containers/cluster/ZeebeClusterTest.java
- core/src/test/java/io/zeebe/containers/examples/ClusterWithEmbeddedGatewaysExampleTest.java
- core/src/test/java/io/zeebe/containers/examples/ClusterWithGatewayExampleTest.java
- core/src/test/java/io/zeebe/containers/examples/ReusableVolumeExampleTest.java
- core/src/test/java/io/zeebe/containers/examples/SingleNodeTest.java
- core/src/test/java/io/zeebe/containers/examples/archive/RestartWithExtractedDataExampleTest.java
- core/src/test/java/io/zeebe/containers/examples/clock/TriggerTimerCatchEventTest.java
- core/src/test/java/io/zeebe/containers/examples/clock/TriggerTimerStartEventTest.java
- core/src/test/java/io/zeebe/containers/examples/exporter/BrokerWithDebugExporterIT.java
- core/src/test/java/io/zeebe/containers/util/TestSupport.java
- engine/src/main/java/io/zeebe/containers/engine/ZeebeClusterEngine.java
- engine/src/main/java/io/zeebe/containers/engine/ZeebeContainerEngine.java
- engine/src/test/java/io/zeebe/containers/engine/ZeebeClusterEngineIT.java
- engine/src/test/java/io/zeebe/containers/engine/ZeebeContainerEngineIT.java
This PR adds support for the REST API, introducing two new methods: `ZeebeGatewayNode#getGrpcAddress` and `ZeebeGatewayNode#getRestAddress`. It also deprecates the old `get*GatewayAddress` variants.
Similarly, there are new `ZeebePort#GATEWAY_REST` and `ZeebePort#GATEWAY_GRPC`, with `ZeebePort#GATEWAY` being deprecated.
closes #623
> feat: add support for REST API

- core/src/main/java/io/zeebe/containers/ZeebeVolume.java
- core/src/test/java/io/zeebe/containers/ZeebeVolumeTest.java
This PR fixes an issue where `ZeebeVolume` would overwrite all other volume binds.
closes #638
> fix: allow multiple volume binds with ZeebeVolume

- core/src/main/java/io/zeebe/containers/ZeebeTopologyWaitStrategy.java
- core/src/test/java/io/zeebe/containers/ZeebeTopologyWaitStrategyTest.java
This PR updates the wait strategy to use the gRPC and REST specific addresses for the client.
> refactor: use rest/grpc for the wait strategy
